//! Generates Rust source code from parsed ModParser data.

use crate::pattern_translator::lua_pattern_to_regex;
use crate::types::*;

// ────────────────────────────────────────────────────────────────────────────
// Public entry points
// ────────────────────────────────────────────────────────────────────────────

/// Generate the complete mod_parser_generated.rs content.
pub fn emit_generated(data: &ParsedModParser) -> Result<String, String> {
    let mut out = String::with_capacity(512 * 1024);

    emit_header(&mut out);
    emit_form_type_enum(&mut out);
    emit_form_patterns(&mut out, &data.forms)?;
    emit_mod_name_map(&mut out, &data.mod_names);
    emit_mod_flag_map(&mut out, &data.mod_flags);
    emit_pre_flag_patterns(&mut out, &data.pre_flags)?;
    emit_mod_tag_patterns(&mut out, &data.mod_tags)?;
    emit_suffix_types(&mut out);
    emit_pen_types(&mut out);
    emit_cost_types(&mut out);
    emit_base_cost_types(&mut out);
    emit_regen_types(&mut out);
    emit_degen_types(&mut out);
    emit_dmg_types(&mut out);
    emit_flag_types(&mut out);
    emit_special_mods(&mut out, &data.special_mods)?;
    emit_scan_functions(&mut out);
    emit_normalize_fn(&mut out);
    emit_pipeline_fn(&mut out);
    emit_count_constants(&mut out, &data.special_mods);

    Ok(out)
}

/// Generate the mod_parser_manual_manifest.rs content (stubs for manual handlers).
pub fn emit_manual_manifest(data: &ParsedModParser) -> Result<String, String> {
    let mut out = String::with_capacity(16 * 1024);

    out.push_str(
        "//! Auto-generated manifest of specialModList entries requiring manual handlers.\n",
    );
    out.push_str("//!\n");
    out.push_str(
        "//! Each entry lists: handler ID, regex pattern, capture count, Lua source line.\n",
    );
    out.push_str("//! Implement handlers in mod_parser_manual.rs.\n\n");

    let manual_entries: Vec<(usize, &SpecialModEntry)> = data
        .special_mods
        .iter()
        .enumerate()
        .filter(|(_, e)| matches!(e.template, SpecialModTemplate::ManualRequired { .. }))
        .collect();

    out.push_str(&format!(
        "/// Number of entries requiring manual handlers.\n\
         pub const MANUAL_ENTRY_COUNT: usize = {};\n\n",
        manual_entries.len()
    ));

    out.push_str(
        "/// Manual handler stubs.\n\
         /// Format: (handler_id, regex_pattern, capture_count, lua_line)\n\
         pub const MANUAL_ENTRIES: &[(&str, &str, usize, usize)] = &[\n",
    );

    for (idx, entry) in &manual_entries {
        let handler_id = format!("manual_{}", idx);
        let (regex_str, capture_count) =
            lua_pattern_to_regex(&entry.pattern.0).unwrap_or_else(|_| (entry.pattern.0.clone(), 0));
        let escaped = escape_rust_string(&regex_str);
        let lua_line = entry.line_number;
        if let SpecialModTemplate::ManualRequired { ref lua_body, .. } = entry.template {
            let body_preview: String = lua_body.chars().take(120).collect();
            let body_escaped = escape_rust_string(&body_preview);
            out.push_str(&format!(
                "    // Lua line {}: {}\n    (\"{}\", r#\"{}\"#, {}, {}),\n",
                lua_line, body_escaped, handler_id, escaped, capture_count, lua_line
            ));
        }
    }

    out.push_str("];\n");

    Ok(out)
}

// ────────────────────────────────────────────────────────────────────────────
// Header & imports
// ────────────────────────────────────────────────────────────────────────────

fn emit_header(out: &mut String) {
    out.push_str(
        "\
#![allow(clippy::all, unused_imports, dead_code, unused_variables, unreachable_patterns, unused_mut)]
//! Auto-generated by modparser-codegen. DO NOT EDIT.

use std::collections::HashMap;
use once_cell::sync::Lazy;
use regex::Regex;
use crate::mod_db::types::*;

",
    );
}

// ────────────────────────────────────────────────────────────────────────────
// FormType enum
// ────────────────────────────────────────────────────────────────────────────

fn emit_form_type_enum(out: &mut String) {
    out.push_str(
        "\
/// Internal form type — maps to ModType + value transforms at construction time.
#[derive(Debug, Clone, PartialEq)]
pub enum FormType {
    Inc,
    Red,
    More,
    Less,
    Base,
    Gain,
    Lose,
    Grants,
    GrantsGlobal,
    Removes,
    Chance,
    Flag,
    TotalCost,
    BaseCost,
    Pen,
    RegenFlat,
    RegenPercent,
    DegenFlat,
    DegenPercent,
    Degen,
    Dmg,
    DmgAttacks,
    DmgSpells,
    DmgBoth,
    Override,
    Doubled,
}

",
    );
}

// ────────────────────────────────────────────────────────────────────────────
// FORM_PATTERNS
// ────────────────────────────────────────────────────────────────────────────

fn emit_form_patterns(out: &mut String, forms: &[FormEntry]) -> Result<(), String> {
    out.push_str(&format!(
        "/// Form patterns from formList ({} entries).\n",
        forms.len()
    ));
    out.push_str(
        "pub static FORM_PATTERNS: Lazy<Vec<(Lazy<Regex>, FormType)>> = Lazy::new(|| vec![\n",
    );

    for entry in forms {
        let (regex_str, _caps) = lua_pattern_to_regex(&entry.pattern.0)
            .map_err(|e| format!("form pattern '{}': {}", entry.pattern.0, e))?;
        let form_variant = form_type_to_rust(&entry.form);
        let escaped = escape_rust_string(&regex_str);
        out.push_str(&format!(
            "    (Lazy::new(|| Regex::new(r#\"{}\"#).unwrap()), FormType::{}),\n",
            escaped, form_variant
        ));
    }

    out.push_str("]);\n\n");
    Ok(())
}

// ────────────────────────────────────────────────────────────────────────────
// MOD_NAME_MAP
// ────────────────────────────────────────────────────────────────────────────

fn emit_mod_name_map(out: &mut String, mod_names: &[ModNameEntry]) {
    out.push_str(
        "/// Entry in the mod name lookup.\n\
         pub struct StaticModNameEntry {\n\
         \x20   pub names: Vec<&'static str>,\n\
         \x20   pub tags: Vec<StaticTag>,\n\
         }\n\n",
    );

    out.push_str(&format!(
        "/// Mod name lookup ({} entries).\n",
        mod_names.len()
    ));
    out.push_str(
        "pub static MOD_NAME_MAP: Lazy<HashMap<&'static str, StaticModNameEntry>> = Lazy::new(|| {\n\
         \x20   let mut m = HashMap::new();\n",
    );

    for entry in mod_names {
        let key = escape_rust_string(&entry.key);
        let names: Vec<String> = entry
            .names
            .iter()
            .map(|n| format!("\"{}\"", escape_rust_string(n)))
            .collect();
        let names_str = names.join(", ");
        let tags_str = emit_static_tags(&entry.tags);
        out.push_str(&format!(
            "    m.insert(\"{}\", StaticModNameEntry {{ names: vec![{}], tags: vec![{}] }});\n",
            key, names_str, tags_str
        ));
    }

    out.push_str("    m\n});\n\n");
}

// ────────────────────────────────────────────────────────────────────────────
// MOD_FLAG_MAP
// ────────────────────────────────────────────────────────────────────────────

fn emit_mod_flag_map(out: &mut String, mod_flags: &[ModFlagEntry]) {
    out.push_str(
        "/// Entry in the mod flag lookup.\n\
         pub struct StaticModFlagEntry {\n\
         \x20   pub flags: ModFlags,\n\
         \x20   pub keyword_flags: KeywordFlags,\n\
         \x20   pub tags: Vec<StaticTag>,\n\
         }\n\n",
    );

    out.push_str(&format!(
        "/// Mod flag lookup ({} entries).\n",
        mod_flags.len()
    ));
    out.push_str(
        "pub static MOD_FLAG_MAP: Lazy<HashMap<&'static str, StaticModFlagEntry>> = Lazy::new(|| {\n\
         \x20   let mut m = HashMap::new();\n",
    );

    for entry in mod_flags {
        let key = escape_rust_string(&entry.key);
        let flags_expr = emit_mod_flags_expr(&entry.flags);
        let kw_expr = emit_keyword_flags_expr(&entry.keyword_flags);
        let tags_str = emit_static_tags(&entry.tags);
        out.push_str(&format!(
            "    m.insert(\"{}\", StaticModFlagEntry {{ flags: {}, keyword_flags: {}, tags: vec![{}] }});\n",
            key, flags_expr, kw_expr, tags_str
        ));
    }

    out.push_str("    m\n});\n\n");
}

// ────────────────────────────────────────────────────────────────────────────
// PRE_FLAG_PATTERNS
// ────────────────────────────────────────────────────────────────────────────

fn emit_pre_flag_patterns(out: &mut String, pre_flags: &[PreFlagEntry]) -> Result<(), String> {
    out.push_str(
        "/// Entry for pre-flag patterns.\n\
         pub struct StaticPreFlagEntry {\n\
         \x20   pub flags: ModFlags,\n\
         \x20   pub keyword_flags: KeywordFlags,\n\
         \x20   pub tags: Vec<StaticTag>,\n\
         \x20   pub add_to_minion: bool,\n\
         \x20   pub add_to_skill: bool,\n\
         \x20   pub add_to_aura: bool,\n\
         \x20   pub new_aura: bool,\n\
         \x20   pub apply_to_enemy: bool,\n\
         }\n\n",
    );

    out.push_str(&format!(
        "/// Pre-flag patterns ({} entries).\n",
        pre_flags.len()
    ));
    out.push_str("pub static PRE_FLAG_PATTERNS: Lazy<Vec<(Lazy<Regex>, StaticPreFlagEntry)>> = Lazy::new(|| vec![\n");

    for entry in pre_flags {
        let (regex_str, _) = lua_pattern_to_regex(&entry.pattern.0)
            .map_err(|e| format!("pre_flag '{}': {}", entry.pattern.0, e))?;
        let escaped = escape_rust_string(&regex_str);
        let flags_expr = emit_mod_flags_expr(&entry.flags);
        let kw_expr = emit_keyword_flags_expr(&entry.keyword_flags);
        let tags_items = emit_static_tag_vec_items(&entry.tags);
        out.push_str(&format!(
            "    (Lazy::new(|| Regex::new(r#\"{}\"#).unwrap()), StaticPreFlagEntry {{\n\
             \x20       flags: {},\n\
             \x20       keyword_flags: {},\n\
             \x20       tags: vec![{}],\n\
             \x20       add_to_minion: {},\n\
             \x20       add_to_skill: {},\n\
             \x20       add_to_aura: {},\n\
             \x20       new_aura: {},\n\
             \x20       apply_to_enemy: {},\n\
             \x20   }}),\n",
            escaped,
            flags_expr,
            kw_expr,
            tags_items,
            entry.add_to_minion,
            entry.add_to_skill,
            entry.add_to_aura,
            entry.new_aura,
            entry.apply_to_enemy,
        ));
    }

    out.push_str("]);\n\n");
    Ok(())
}

// ────────────────────────────────────────────────────────────────────────────
// MOD_TAG_PATTERNS
// ────────────────────────────────────────────────────────────────────────────

fn emit_mod_tag_patterns(out: &mut String, mod_tags: &[ModTagEntry]) -> Result<(), String> {
    out.push_str(
        "/// Entry for mod tag patterns.\n\
         pub struct StaticModTagEntry {\n\
         \x20   pub tags: Vec<StaticTag>,\n\
         }\n\n",
    );

    out.push_str(&format!(
        "/// Mod tag patterns ({} entries).\n",
        mod_tags.len()
    ));
    out.push_str("pub static MOD_TAG_PATTERNS: Lazy<Vec<(Lazy<Regex>, StaticModTagEntry)>> = Lazy::new(|| vec![\n");

    for entry in mod_tags {
        let (regex_str, _) = lua_pattern_to_regex(&entry.pattern.0)
            .map_err(|e| format!("mod_tag '{}': {}", entry.pattern.0, e))?;
        let escaped = escape_rust_string(&regex_str);
        let tags_items = emit_static_tag_vec_items(&entry.tags);
        out.push_str(&format!(
            "    (Lazy::new(|| Regex::new(r#\"{}\"#).unwrap()), StaticModTagEntry {{\n\
             \x20       tags: vec![{}],\n\
             \x20   }}),\n",
            escaped, tags_items
        ));
    }

    out.push_str("]);\n\n");
    Ok(())
}

// ────────────────────────────────────────────────────────────────────────────
// Special lookup tables
// ────────────────────────────────────────────────────────────────────────────

fn emit_suffix_types(out: &mut String) {
    out.push_str(
        "/// Suffix types lookup (mirrors suffixTypes in ModParser.lua).\n\
         pub static SUFFIX_TYPES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {\n\
         \x20   let mut m = HashMap::new();\n",
    );

    let suffixes = [
        ("as extra lightning damage", "GainAsLightning"),
        ("added as lightning damage", "GainAsLightning"),
        ("gained as extra lightning damage", "GainAsLightning"),
        ("as extra cold damage", "GainAsCold"),
        ("added as cold damage", "GainAsCold"),
        ("gained as extra cold damage", "GainAsCold"),
        ("as extra fire damage", "GainAsFire"),
        ("added as fire damage", "GainAsFire"),
        ("gained as extra fire damage", "GainAsFire"),
        ("as extra chaos damage", "GainAsChaos"),
        ("added as chaos damage", "GainAsChaos"),
        ("gained as extra chaos damage", "GainAsChaos"),
        ("converted to lightning", "ConvertToLightning"),
        ("converted to lightning damage", "ConvertToLightning"),
        ("converted to cold damage", "ConvertToCold"),
        ("converted to fire damage", "ConvertToFire"),
        ("converted to fire", "ConvertToFire"),
        ("converted to chaos damage", "ConvertToChaos"),
        ("added as energy shield", "GainAsEnergyShield"),
        ("as extra maximum energy shield", "GainAsEnergyShield"),
        ("converted to energy shield", "ConvertToEnergyShield"),
        ("as extra armour", "GainAsArmour"),
        ("as physical damage", "AsPhysical"),
        ("as lightning damage", "AsLightning"),
        ("as cold damage", "AsCold"),
        ("as fire damage", "AsFire"),
        ("as fire", "AsFire"),
        ("as chaos damage", "AsChaos"),
        ("leeched as life and mana", "Leech"),
        ("leeched as life", "LifeLeech"),
        ("is leeched as life", "LifeLeech"),
        ("leeched as mana", "ManaLeech"),
        ("is leeched as mana", "ManaLeech"),
        ("leeched as energy shield", "EnergyShieldLeech"),
        ("is leeched as energy shield", "EnergyShieldLeech"),
    ];

    for (k, v) in &suffixes {
        out.push_str(&format!("    m.insert(\"{}\", \"{}\");\n", k, v));
    }

    out.push_str("    m\n});\n\n");
}

fn emit_pen_types(out: &mut String) {
    out.push_str(
        "/// Pen types lookup.\n\
         pub static PEN_TYPES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {\n\
         \x20   let mut m = HashMap::new();\n",
    );

    let pens = [
        ("lightning resistance", "LightningPenetration"),
        ("cold resistance", "ColdPenetration"),
        ("fire resistance", "FirePenetration"),
        ("elemental resistance", "ElementalPenetration"),
        ("elemental resistances", "ElementalPenetration"),
        ("chaos resistance", "ChaosPenetration"),
    ];

    for (k, v) in &pens {
        out.push_str(&format!("    m.insert(\"{}\", \"{}\");\n", k, v));
    }

    out.push_str("    m\n});\n\n");
}

fn emit_cost_types(out: &mut String) {
    emit_resource_suffixed_map(out, "COST_TYPES", "Cost", "Cost types lookup.");
}

fn emit_base_cost_types(out: &mut String) {
    emit_resource_suffixed_map(
        out,
        "BASE_COST_TYPES",
        "CostNoMult",
        "Base cost types lookup.",
    );
}

fn emit_regen_types(out: &mut String) {
    emit_resource_suffixed_map(out, "REGEN_TYPES", "Regen", "Regen types lookup.");
}

fn emit_degen_types(out: &mut String) {
    emit_resource_suffixed_map(out, "DEGEN_TYPES", "Degen", "Degen types lookup.");
}

/// Emit a resource type lookup with the given suffix.
fn emit_resource_suffixed_map(out: &mut String, name: &str, suffix: &str, doc: &str) {
    out.push_str(&format!(
        "/// {}\n\
         pub static {}: Lazy<HashMap<&'static str, Vec<String>>> = Lazy::new(|| {{\n\
         \x20   let mut m: HashMap<&'static str, Vec<String>> = HashMap::new();\n",
        doc, name
    ));

    // resourceTypes from ModParser.lua
    let resources: Vec<(&str, Vec<&str>)> = vec![
        ("life", vec!["Life"]),
        ("mana", vec!["Mana"]),
        ("energy shield", vec!["EnergyShield"]),
        ("life and mana", vec!["Life", "Mana"]),
        ("life and energy shield", vec!["Life", "EnergyShield"]),
        (
            "life, mana and energy shield",
            vec!["Life", "Mana", "EnergyShield"],
        ),
        (
            "life, energy shield and mana",
            vec!["Life", "Mana", "EnergyShield"],
        ),
        ("mana and life", vec!["Life", "Mana"]),
        ("mana and energy shield", vec!["Mana", "EnergyShield"]),
        (
            "mana, life and energy shield",
            vec!["Life", "Mana", "EnergyShield"],
        ),
        (
            "mana, energy shield and life",
            vec!["Life", "Mana", "EnergyShield"],
        ),
        ("energy shield and life", vec!["Life", "EnergyShield"]),
        ("energy shield and mana", vec!["Mana", "EnergyShield"]),
        (
            "energy shield, life and mana",
            vec!["Life", "Mana", "EnergyShield"],
        ),
        (
            "energy shield, mana and life",
            vec!["Life", "Mana", "EnergyShield"],
        ),
        ("rage", vec!["Rage"]),
    ];

    // Also include "maximum X" variants
    let mut all_resources = resources.clone();
    for (key, vals) in &resources {
        all_resources.push((&"", vals.clone())); // placeholder, replaced below
    }
    // Actually, build it properly:
    out.push_str("    // Base resource types\n");
    for (key, vals) in &resources {
        let suffixed: Vec<String> = vals.iter().map(|v| format!("{}{}", v, suffix)).collect();
        let vals_str = suffixed
            .iter()
            .map(|s| format!("\"{}\".to_string()", s))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    m.insert(\"{}\", vec![{}]);\n", key, vals_str));
    }

    out.push_str("    // Maximum resource types\n");
    for (key, vals) in &resources {
        let max_key = format!("maximum {}", key);
        let suffixed: Vec<String> = vals.iter().map(|v| format!("{}{}", v, suffix)).collect();
        let vals_str = suffixed
            .iter()
            .map(|s| format!("\"{}\".to_string()", s))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "    m.insert(\"{}\", vec![{}]);\n",
            max_key, vals_str
        ));
    }

    out.push_str("    m\n});\n\n");
}

fn emit_dmg_types(out: &mut String) {
    out.push_str(
        "/// Damage type lookup.\n\
         pub static DMG_TYPES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {\n\
         \x20   let mut m = HashMap::new();\n\
         \x20   m.insert(\"physical\", \"Physical\");\n\
         \x20   m.insert(\"lightning\", \"Lightning\");\n\
         \x20   m.insert(\"cold\", \"Cold\");\n\
         \x20   m.insert(\"fire\", \"Fire\");\n\
         \x20   m.insert(\"chaos\", \"Chaos\");\n\
         \x20   m\n\
         });\n\n",
    );
}

fn emit_flag_types(out: &mut String) {
    out.push_str(
        "/// Flag types lookup (maps flag names to stat names).\n\
         pub static FLAG_TYPES: Lazy<HashMap<&'static str, FlagTypeValue>> = Lazy::new(|| {\n\
         \x20   let mut m = HashMap::new();\n",
    );

    // Simple condition flags
    let simple_flags = [
        ("phasing", "Condition:Phasing"),
        ("onslaught", "Condition:Onslaught"),
        ("rampage", "Condition:Rampage"),
        ("soul eater", "Condition:CanHaveSoulEater"),
        ("adrenaline", "Condition:Adrenaline"),
        ("elusive", "Condition:CanBeElusive"),
        ("arcane surge", "Condition:ArcaneSurge"),
        ("fortify", "Condition:Fortified"),
        ("fortified", "Condition:Fortified"),
        ("unholy might", "Condition:UnholyMight"),
        ("chaotic might", "Condition:ChaoticMight"),
        ("lesser brutal shrine buff", "Condition:LesserBrutalShrine"),
        (
            "lesser massive shrine buff",
            "Condition:LesserMassiveShrine",
        ),
        ("tailwind", "Condition:Tailwind"),
        ("intimidated", "Condition:Intimidated"),
        ("crushed", "Condition:Crushed"),
        ("chilled", "Condition:Chilled"),
        ("blinded", "Condition:Blinded"),
        ("no life regeneration", "NoLifeRegen"),
        ("unnerved", "Condition:Unnerved"),
        ("malediction", "HasMalediction"),
        ("debilitated", "Condition:Debilitated"),
        ("acceleration shrine buff", "Condition:AccelerationShrine"),
        ("brutal shrine buff", "Condition:BrutalShrine"),
        ("diamond shrine buff", "Condition:DiamondShrine"),
        ("echoing shrine buff", "Condition:EchoingShrine"),
        ("gloom shrine buff", "Condition:GloomShrine"),
        (
            "greater freezing shrine buff",
            "Condition:GreaterFreezingShrine",
        ),
        (
            "greater shocking shrine buff",
            "Condition:GreaterShockingShrine",
        ),
        (
            "greater skeletal shrine buff",
            "Condition:GreaterSkeletalShrine",
        ),
        ("impenetrable shrine buff", "Condition:ImpenetrableShrine"),
        ("massive shrine buff", "Condition:MassiveShrine"),
        ("replenishing shrine buff", "Condition:ReplenishingShrine"),
        ("resistance shrine buff", "Condition:ResistanceShrine"),
        ("resonating shrine buff", "Condition:ResonatingShrine"),
    ];

    for (k, v) in &simple_flags {
        out.push_str(&format!(
            "    m.insert(\"{}\", FlagTypeValue::Simple(\"{}\".to_string()));\n",
            k, v
        ));
    }

    // Hexproof is special: { name = "CurseEffectOnSelf", value = -100, type = "MORE" }
    out.push_str(
        "    m.insert(\"hexproof\", FlagTypeValue::Complex { name: \"CurseEffectOnSelf\".to_string(), mod_type: \"MORE\".to_string(), value: -100.0 });\n",
    );

    out.push_str("    m\n});\n\n");

    // The FlagTypeValue enum
    out.push_str(
        "/// Value type for flag type entries.\n\
         #[derive(Debug, Clone)]\n\
         pub enum FlagTypeValue {\n\
         \x20   Simple(String),\n\
         \x20   Complex { name: String, mod_type: String, value: f64 },\n\
         }\n\n",
    );
}

// ────────────────────────────────────────────────────────────────────────────
// Special mods
// ────────────────────────────────────────────────────────────────────────────

fn emit_special_mods(out: &mut String, special_mods: &[SpecialModEntry]) -> Result<(), String> {
    out.push_str(&format!(
        "/// Special mod patterns ({} entries).\n",
        special_mods.len()
    ));
    out.push_str("pub static SPECIAL_MOD_PATTERNS: Lazy<Vec<Lazy<Regex>>> = Lazy::new(|| vec![\n");

    for entry in special_mods {
        let (regex_str, _) = lua_pattern_to_regex(&entry.pattern.0)
            .map_err(|e| format!("special_mod '{}': {}", entry.pattern.0, e))?;
        let escaped = escape_rust_string(&regex_str);
        out.push_str(&format!(
            "    Lazy::new(|| Regex::new(r#\"{}\"#).unwrap()),\n",
            escaped
        ));
    }

    out.push_str("]);\n\n");

    // Now emit the handler function
    emit_special_mod_handler(out, special_mods)?;

    Ok(())
}

fn emit_special_mod_handler(
    out: &mut String,
    special_mods: &[SpecialModEntry],
) -> Result<(), String> {
    out.push_str(
        "/// Handle a matched special mod by index.\n\
         /// Returns Some(Vec<Mod>) if handled, None if manual handler needed.\n\
         fn handle_special_mod(\n\
         \x20   idx: usize,\n\
         \x20   caps: &regex::Captures,\n\
         \x20   source: &ModSource,\n\
         \x20   manual_handler: &dyn Fn(&str, &regex::Captures, &ModSource) -> Vec<Mod>,\n\
         ) -> Vec<Mod> {\n\
         \x20   match idx {\n",
    );

    for (i, entry) in special_mods.iter().enumerate() {
        out.push_str(&format!("        {} => {{\n", i));
        emit_template_handler(out, &entry.template, i)?;
        out.push_str("        }\n");
    }

    out.push_str(
        "        _ => vec![],\n\
         \x20   }\n\
         }\n\n",
    );

    Ok(())
}

fn emit_template_handler(
    out: &mut String,
    template: &SpecialModTemplate,
    idx: usize,
) -> Result<(), String> {
    match template {
        SpecialModTemplate::StaticMods(calls) => {
            if calls.is_empty() {
                out.push_str("            vec![]\n");
            } else {
                out.push_str("            vec![\n");
                for call in calls {
                    emit_mod_call_construction(out, call, "source");
                }
                out.push_str("            ]\n");
            }
        }
        SpecialModTemplate::SimpleFn(calls) => {
            // Extract the first capture as num
            out.push_str(
                "            let num_str = caps.get(1).map(|m| m.as_str()).unwrap_or(\"0\");\n",
            );
            out.push_str("            let num: f64 = num_str.parse().unwrap_or(0.0);\n");
            if calls.is_empty() {
                out.push_str("            vec![]\n");
            } else {
                out.push_str("            vec![\n");
                for call in calls {
                    emit_mod_call_construction(out, call, "source");
                }
                out.push_str("            ]\n");
            }
        }
        SpecialModTemplate::HelperCall { helper, args } => {
            // Generate a call to a helper stub
            let handler_id = format!("helper_{}_{}", helper, idx);
            out.push_str(&format!(
                "            // Helper: {}({})\n",
                helper,
                args.join(", ")
            ));
            out.push_str(&format!(
                "            manual_handler(\"{}\", caps, source)\n",
                handler_id
            ));
        }
        SpecialModTemplate::DamageConversion { stat_prefix, .. } => {
            out.push_str(
                "            let num_str = caps.get(1).map(|m| m.as_str()).unwrap_or(\"0\");\n",
            );
            out.push_str("            let num: f64 = num_str.parse().unwrap_or(0.0);\n");
            out.push_str(
                "            let dmg_type = caps.get(2).map(|m| m.as_str()).unwrap_or(\"\");\n",
            );
            out.push_str("            let type_cap = capitalize_first(dmg_type);\n");
            let prefix = escape_rust_string(stat_prefix);
            out.push_str(&format!(
                "            let stat_name = format!(\"{{}}ConvertTo{{}}\", \"{}\", type_cap);\n",
                prefix
            ));
            out.push_str("            vec![Mod {\n");
            out.push_str("                name: stat_name,\n");
            out.push_str("                mod_type: ModType::Base,\n");
            out.push_str("                value: ModValue::Number(num),\n");
            out.push_str("                flags: ModFlags::NONE,\n");
            out.push_str("                keyword_flags: KeywordFlags::NONE,\n");
            out.push_str("                tags: vec![],\n");
            out.push_str("                source: source.clone(),\n");
            out.push_str("            }]\n");
        }
        SpecialModTemplate::DamageGainAs { stat_prefix, .. } => {
            out.push_str(
                "            let num_str = caps.get(1).map(|m| m.as_str()).unwrap_or(\"0\");\n",
            );
            out.push_str("            let num: f64 = num_str.parse().unwrap_or(0.0);\n");
            out.push_str(
                "            let dmg_type = caps.get(2).map(|m| m.as_str()).unwrap_or(\"\");\n",
            );
            out.push_str("            let type_cap = capitalize_first(dmg_type);\n");
            let prefix = escape_rust_string(stat_prefix);
            out.push_str(&format!(
                "            let stat_name = format!(\"{{}}GainAs{{}}\", \"{}\", type_cap);\n",
                prefix
            ));
            out.push_str("            vec![Mod {\n");
            out.push_str("                name: stat_name,\n");
            out.push_str("                mod_type: ModType::Base,\n");
            out.push_str("                value: ModValue::Number(num),\n");
            out.push_str("                flags: ModFlags::NONE,\n");
            out.push_str("                keyword_flags: KeywordFlags::NONE,\n");
            out.push_str("                tags: vec![],\n");
            out.push_str("                source: source.clone(),\n");
            out.push_str("            }]\n");
        }
        SpecialModTemplate::NumericScaling { mod_call, factor } => {
            out.push_str(
                "            let num_str = caps.get(1).map(|m| m.as_str()).unwrap_or(\"0\");\n",
            );
            out.push_str("            let num: f64 = num_str.parse().unwrap_or(0.0);\n");
            out.push_str(&format!("            let scaled = num * {:.6};\n", factor));
            emit_single_mod_call_with_value(out, mod_call, "scaled", "source");
        }
        SpecialModTemplate::EnemyModifier(calls) => {
            if calls.is_empty() {
                out.push_str("            vec![]\n");
            } else {
                // For EnemyModifier, we wrap the inner mod in an EnemyModifier LIST mod
                out.push_str(
                    "            let num_str = caps.get(1).map(|m| m.as_str()).unwrap_or(\"0\");\n",
                );
                out.push_str("            let num: f64 = num_str.parse().unwrap_or(0.0);\n");
                out.push_str("            // EnemyModifier wrapper — simplified\n");
                out.push_str("            vec![\n");
                for call in calls {
                    emit_mod_call_construction(out, call, "source");
                }
                out.push_str("            ]\n");
            }
        }
        SpecialModTemplate::MinionModifier(calls) => {
            if calls.is_empty() {
                out.push_str("            vec![]\n");
            } else {
                out.push_str(
                    "            let num_str = caps.get(1).map(|m| m.as_str()).unwrap_or(\"0\");\n",
                );
                out.push_str("            let num: f64 = num_str.parse().unwrap_or(0.0);\n");
                out.push_str("            // MinionModifier wrapper — simplified\n");
                out.push_str("            vec![\n");
                for call in calls {
                    emit_mod_call_construction(out, call, "source");
                }
                out.push_str("            ]\n");
            }
        }
        SpecialModTemplate::ManualRequired {
            lua_body,
            line_number,
        } => {
            let handler_id = format!("manual_{}", idx);
            let body_preview: String = lua_body.chars().take(80).collect();
            let comment = escape_rust_string(&body_preview);
            out.push_str(&format!(
                "            // Manual: Lua line {} — {}\n",
                line_number, comment
            ));
            out.push_str(&format!(
                "            manual_handler(\"{}\", caps, source)\n",
                handler_id
            ));
        }
    }
    Ok(())
}

/// Emit a single mod() or flag() construction from a LuaModCall.
fn emit_mod_call_construction(out: &mut String, call: &LuaModCall, source_var: &str) {
    let name = escape_rust_string(&call.name);
    let mod_type = lua_mod_type_to_rust(&call.mod_type);
    let value_expr = lua_value_to_rust(&call.value, &call.mod_type);
    let flags_expr = call
        .flags
        .as_ref()
        .map(|f| emit_single_mod_flag(f))
        .unwrap_or_else(|| "ModFlags::NONE".to_string());
    let kw_expr = call
        .keyword_flags
        .as_ref()
        .map(|f| emit_single_keyword_flag(f))
        .unwrap_or_else(|| "KeywordFlags::NONE".to_string());

    if call.dynamic_name {
        // For dynamic names, we need to use captures at runtime
        // For now, emit a placeholder that uses the static name
        out.push_str(&format!(
            "                Mod {{\n\
             \x20                   name: \"{}\".to_string(),\n\
             \x20                   mod_type: {},\n\
             \x20                   value: {},\n\
             \x20                   flags: {},\n\
             \x20                   keyword_flags: {},\n\
             \x20                   tags: vec![],\n\
             \x20                   source: {}.clone(),\n\
             \x20               }},\n",
            name, mod_type, value_expr, flags_expr, kw_expr, source_var
        ));
    } else {
        out.push_str(&format!(
            "                Mod {{\n\
             \x20                   name: \"{}\".to_string(),\n\
             \x20                   mod_type: {},\n\
             \x20                   value: {},\n\
             \x20                   flags: {},\n\
             \x20                   keyword_flags: {},\n\
             \x20                   tags: vec![],\n\
             \x20                   source: {}.clone(),\n\
             \x20               }},\n",
            name, mod_type, value_expr, flags_expr, kw_expr, source_var
        ));
    }
}

fn emit_single_mod_call_with_value(
    out: &mut String,
    call: &LuaModCall,
    value_var: &str,
    source_var: &str,
) {
    let name = escape_rust_string(&call.name);
    let mod_type = lua_mod_type_to_rust(&call.mod_type);
    let flags_expr = call
        .flags
        .as_ref()
        .map(|f| emit_single_mod_flag(f))
        .unwrap_or_else(|| "ModFlags::NONE".to_string());
    let kw_expr = call
        .keyword_flags
        .as_ref()
        .map(|f| emit_single_keyword_flag(f))
        .unwrap_or_else(|| "KeywordFlags::NONE".to_string());

    out.push_str(&format!(
        "            vec![Mod {{\n\
         \x20               name: \"{}\".to_string(),\n\
         \x20               mod_type: {},\n\
         \x20               value: ModValue::Number({}),\n\
         \x20               flags: {},\n\
         \x20               keyword_flags: {},\n\
         \x20               tags: vec![],\n\
         \x20               source: {}.clone(),\n\
         \x20           }}]\n",
        name, mod_type, value_var, flags_expr, kw_expr, source_var
    ));
}

// ────────────────────────────────────────────────────────────────────────────
// Scan functions
// ────────────────────────────────────────────────────────────────────────────

fn emit_scan_functions(out: &mut String) {
    out.push_str(
        r#"
/// StaticTag type for parsed tag data.
#[derive(Debug, Clone)]
pub enum StaticTag {
    Condition { var: String, neg: bool },
    Multiplier { var: String, div: f64, limit: Option<f64>, base: f64 },
    MultiplierThreshold { var: String, threshold: f64, upper: bool },
    PerStat { stat: String, div: f64, limit: Option<f64>, base: f64 },
    StatThreshold { stat: String, threshold: f64, upper: bool },
    GlobalEffect { effect_type: String, unscalable: bool },
    SkillName { name: String },
    SkillId { id: String },
    SkillType { skill_type: u32 },
    SlotName { slot_name: String, neg: bool },
    SocketedIn { slot_name: String },
    ItemCondition { var: String, neg: bool },
    ActorCondition { actor: String, var: String, neg: bool },
    Limit { limit: f64 },
    ModFlagOr { mod_flags: ModFlags },
    KeywordFlagAnd { keyword_flags: KeywordFlags },
    Unknown { raw: String },
}

impl StaticTag {
    /// Convert to the runtime ModTag type.
    pub fn to_mod_tag(&self) -> ModTag {
        match self {
            StaticTag::Condition { var, neg } => ModTag::Condition { var: var.clone(), neg: *neg },
            StaticTag::Multiplier { var, div, limit, base } => ModTag::Multiplier { var: var.clone(), div: *div, limit: *limit, base: *base },
            StaticTag::MultiplierThreshold { var, threshold, upper } => ModTag::MultiplierThreshold { var: var.clone(), threshold: *threshold, upper: *upper },
            StaticTag::PerStat { stat, div, limit, base } => ModTag::PerStat { stat: stat.clone(), div: *div, limit: *limit, base: *base },
            StaticTag::StatThreshold { stat, threshold, upper } => ModTag::StatThreshold { stat: stat.clone(), threshold: *threshold, upper: *upper },
            StaticTag::GlobalEffect { effect_type, unscalable } => ModTag::GlobalEffect { effect_type: effect_type.clone(), unscalable: *unscalable },
            StaticTag::SkillName { name } => ModTag::SkillName { name: name.clone() },
            StaticTag::SkillId { id } => ModTag::SkillId { id: id.clone() },
            StaticTag::SkillType { skill_type } => ModTag::SkillType { skill_type: *skill_type },
            StaticTag::SlotName { slot_name, neg } => ModTag::SlotName { slot_name: slot_name.clone(), neg: *neg },
            StaticTag::SocketedIn { slot_name } => ModTag::SocketedIn { slot_name: slot_name.clone() },
            StaticTag::ItemCondition { var, neg } => ModTag::ItemCondition { var: var.clone(), neg: *neg },
            StaticTag::ActorCondition { actor, var, neg } => ModTag::ActorCondition { actor: actor.clone(), var: var.clone(), neg: *neg },
            StaticTag::Limit { limit } => ModTag::Limit { limit: *limit },
            StaticTag::ModFlagOr { mod_flags } => ModTag::ModFlagOr { mod_flags: *mod_flags },
            StaticTag::KeywordFlagAnd { keyword_flags } => ModTag::KeywordFlagAnd { keyword_flags: *keyword_flags },
            StaticTag::Unknown { .. } => ModTag::Condition { var: "_unsupported".to_string(), neg: false },
        }
    }
}

/// Capitalize the first letter of a string.
fn capitalize_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Find the earliest regex match among patterns, breaking ties by longest match, then longest pattern.
/// Returns (pattern_index, captures, match_start, match_end).
fn scan_regex<'a, T>(line: &'a str, patterns: &[(Lazy<Regex>, T)]) -> Option<(usize, regex::Captures<'a>, usize, usize)>
where
    T: std::fmt::Debug,
{
    let mut best: Option<(usize, usize, usize, usize, usize)> = None; // (idx, start, end, match_len, pat_len)

    for (i, (re, _)) in patterns.iter().enumerate() {
        if let Some(m) = re.find(line) {
            let start = m.start();
            let end = m.end();
            let match_len = end - start;
            let pat_len = re.as_str().len();

            let is_better = match best {
                None => true,
                Some((_, bs, be, bml, bpl)) => {
                    start < bs
                        || (start == bs && match_len > bml)
                        || (start == bs && match_len == bml && pat_len > bpl)
                }
            };

            if is_better {
                best = Some((i, start, end, match_len, pat_len));
            }
        }
    }

    if let Some((idx, start, end, _, _)) = best {
        let re = &patterns[idx].0;
        let caps = re.captures(line)?;
        Some((idx, caps, start, end))
    } else {
        None
    }
}

/// Scan regex patterns stored in a Vec (for Lazy<Vec<...>> data).
fn scan_regex_vec<'a, T>(line: &'a str, patterns: &[(Lazy<Regex>, T)]) -> Option<(usize, regex::Captures<'a>, usize, usize)>
where
    T: std::fmt::Debug,
{
    scan_regex(line, patterns)
}

/// Find the earliest plain-text substring match among keys in a HashMap.
/// Returns (key, start, end, entry).
fn scan_plain<'a, V>(line: &str, map: &'a HashMap<&str, V>) -> Option<(&'a str, usize, usize, &'a V)> {
    let lower = line.to_lowercase();
    let mut best: Option<(&'a str, usize, usize, &'a V)> = None;

    for (key, val) in map.iter() {
        if let Some(pos) = lower.find(key) {
            let end = pos + key.len();
            let is_better = match best {
                None => true,
                Some((_, bs, be, _)) => {
                    let best_len = be - bs;
                    let this_len = end - pos;
                    pos < bs
                        || (pos == bs && this_len > best_len)
                        || (pos == bs && this_len == best_len && key.len() > (be - bs))
                }
            };
            if is_better {
                best = Some((key, pos, end, val));
            }
        }
    }

    best
}

/// Excise a matched portion from a line: text_before + text_after.
fn excise(line: &str, start: usize, end: usize) -> String {
    let before = &line[..start];
    let after = &line[end..];
    format!("{}{}", before, after)
}

"#,
    );
}

// ────────────────────────────────────────────────────────────────────────────
// Normalize function
// ────────────────────────────────────────────────────────────────────────────

fn emit_normalize_fn(out: &mut String) {
    out.push_str(
        r#"
/// Strip PoB colour codes: ^8, ^7, ^x followed by 6 hex chars.
fn strip_colour_codes(line: &str) -> String {
    static COLOUR_RE: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"\^[0-9]|\^x[0-9a-fA-F]{6}").unwrap()
    });
    COLOUR_RE.replace_all(line, "").to_string()
}

/// Normalize a mod line: strip colour codes, lowercase, trim, append trailing space.
fn normalize(line: &str) -> String {
    let stripped = strip_colour_codes(line);
    let lower = stripped.to_lowercase();
    let trimmed = lower.trim().to_string();
    trimmed + " "
}

"#,
    );
}

// ────────────────────────────────────────────────────────────────────────────
// Main pipeline function
// ────────────────────────────────────────────────────────────────────────────

fn emit_pipeline_fn(out: &mut String) {
    out.push_str(
        r##"
/// Main entry point: parse a mod line into a list of Mod structs.
///
/// Implements the full PoB parsing pipeline:
/// 1. Normalize
/// 2. Try specialModList (full-line match)
/// 3. Extract pre-flags
/// 4. Match form (INC/MORE/BASE/etc.)
/// 5. Extract mod tags (suffix conditions, up to 2 passes)
/// 6. Look up mod name
/// 7. Extract mod flags
/// 8. Construct mods
pub fn parse_mod_generated(
    line: &str,
    source: &ModSource,
    manual_handler: &dyn Fn(&str, &regex::Captures, &ModSource) -> Vec<Mod>,
) -> Vec<Mod> {
    let normalized = normalize(line);
    let norm = normalized.as_str();

    // Step 2: Try special mods (full-line match — must consume entire line)
    let special_patterns = &*SPECIAL_MOD_PATTERNS;
    for (i, re) in special_patterns.iter().enumerate() {
        if let Some(caps) = re.captures(norm.trim()) {
            // Check full-line match: the overall match must cover the entire trimmed line
            if let Some(m) = caps.get(0) {
                if m.start() == 0 && m.end() == norm.trim().len() {
                    return handle_special_mod(i, &caps, source, manual_handler);
                }
            }
        }
    }

    // From here on, work with the normalized line (with trailing space)
    let mut line = norm.to_string();

    // Step 3: Extract pre-flags
    let mut pre_flags = ModFlags::NONE;
    let mut pre_keyword_flags = KeywordFlags::NONE;
    let mut pre_tags: Vec<ModTag> = Vec::new();
    let mut add_to_minion = false;
    let mut add_to_skill = false;
    let mut add_to_aura = false;
    let mut new_aura = false;
    let mut apply_to_enemy = false;

    {
        let patterns = &*PRE_FLAG_PATTERNS;
        let pat_slice: Vec<(&Lazy<Regex>, &StaticPreFlagEntry)> = patterns.iter().map(|(r, e)| (r, e)).collect();
        // Build a slice-compatible view
        if let Some((idx, caps, start, end)) = scan_regex_for_pre_flags(&line, patterns) {
            let entry = &patterns[idx].1;
            pre_flags = pre_flags | entry.flags;
            pre_keyword_flags = pre_keyword_flags | entry.keyword_flags;
            for t in &entry.tags {
                pre_tags.push(t.to_mod_tag());
            }
            add_to_minion = entry.add_to_minion;
            add_to_skill = entry.add_to_skill;
            add_to_aura = entry.add_to_aura;
            new_aura = entry.new_aura;
            apply_to_enemy = entry.apply_to_enemy;
            line = excise(&line, start, end);
        }
    }

    // Step 4: Scan for modifier form
    let form_result = scan_form_patterns(&line);
    let (form_type, form_num, form_caps_extra) = match form_result {
        Some(v) => v,
        None => return vec![], // No form match = unparseable
    };
    // Excise the form match from the line
    if let Some((_idx, _caps, start, end)) = scan_regex(&line, &*FORM_PATTERNS) {
        line = excise(&line, start, end);
    }

    // Step 5: Extract mod tags (up to 2 passes)
    let mut mod_tags: Vec<ModTag> = Vec::new();
    {
        let patterns = &*MOD_TAG_PATTERNS;
        if let Some((idx, caps, start, end)) = scan_regex_for_mod_tags(&line, patterns) {
            let entry = &patterns[idx].1;
            for t in &entry.tags {
                mod_tags.push(t.to_mod_tag());
            }
            line = excise(&line, start, end);

            // Second pass
            if let Some((idx2, caps2, start2, end2)) = scan_regex_for_mod_tags(&line, patterns) {
                let entry2 = &patterns[idx2].1;
                for t in &entry2.tags {
                    mod_tags.push(t.to_mod_tag());
                }
                line = excise(&line, start2, end2);
            }
        }
    }

    // Step 6: Look up mod name
    let mod_name_result: Option<(Vec<String>, Vec<ModTag>)>;

    match &form_type {
        FormType::Pen => {
            // Use PEN_TYPES for name lookup
            if let Some((key, start, end, val)) = scan_plain(&line, &*PEN_TYPES) {
                mod_name_result = Some((vec![val.to_string()], vec![]));
                line = excise(&line, start, end);
                // Also scan modNameList to excise it
                if let Some((_, s2, e2, _)) = scan_plain(&line, &*MOD_NAME_MAP) {
                    line = excise(&line, s2, e2);
                }
            } else {
                return vec![];
            }
        }
        FormType::BaseCost => {
            if let Some((key, start, end, val)) = scan_plain_vec(&line, &*BASE_COST_TYPES) {
                mod_name_result = Some((val.clone(), vec![]));
                line = excise(&line, start, end);
                if let Some((_, s2, e2, _)) = scan_plain(&line, &*MOD_NAME_MAP) {
                    line = excise(&line, s2, e2);
                }
            } else {
                return vec![];
            }
        }
        FormType::TotalCost => {
            if let Some((key, start, end, val)) = scan_plain_vec(&line, &*COST_TYPES) {
                mod_name_result = Some((val.clone(), vec![]));
                line = excise(&line, start, end);
                if let Some((_, s2, e2, _)) = scan_plain(&line, &*MOD_NAME_MAP) {
                    line = excise(&line, s2, e2);
                }
            } else {
                return vec![];
            }
        }
        FormType::Flag => {
            // For FLAG form, the "value" from formCap[1] is looked up in flagTypes
            // Actually the FLAG form scans flagTypes first
            if let Some((key, start, end, val)) = scan_plain(&line, &*FLAG_TYPES) {
                line = excise(&line, start, end);
            }
            // Then scan modNameList
            if let Some((key, start, end, entry)) = scan_plain(&line, &*MOD_NAME_MAP) {
                let names: Vec<String> = entry.names.iter().map(|s| s.to_string()).collect();
                let tags: Vec<ModTag> = entry.tags.iter().map(|t| t.to_mod_tag()).collect();
                mod_name_result = Some((names, tags));
                line = excise(&line, start, end);
            } else {
                mod_name_result = None;
            }
        }
        _ => {
            // Standard name lookup
            if let Some((key, start, end, entry)) = scan_plain(&line, &*MOD_NAME_MAP) {
                let names: Vec<String> = entry.names.iter().map(|s| s.to_string()).collect();
                let tags: Vec<ModTag> = entry.tags.iter().map(|t| t.to_mod_tag()).collect();
                mod_name_result = Some((names, tags));
                line = excise(&line, start, end);
            } else {
                mod_name_result = None;
            }
        }
    }

    // Step 7: Extract mod flags (weapon/skill type)
    let mut mod_flag_flags = ModFlags::NONE;
    let mut mod_flag_kw = KeywordFlags::NONE;
    let mut mod_flag_tags: Vec<ModTag> = Vec::new();
    if let Some((key, start, end, entry)) = scan_plain(&line, &*MOD_FLAG_MAP) {
        mod_flag_flags = entry.flags;
        mod_flag_kw = entry.keyword_flags;
        for t in entry.tags.iter() {
            mod_flag_tags.push(t.to_mod_tag());
        }
        line = excise(&line, start, end);
    }

    // Step 8: Handle form-specific suffix and regen/degen/dmg lookups
    let mut mod_suffix = String::new();
    match &form_type {
        FormType::Base | FormType::Gain | FormType::Lose | FormType::Grants | FormType::GrantsGlobal | FormType::Removes => {
            if let Some((_, start, end, val)) = scan_plain(&line, &*SUFFIX_TYPES) {
                mod_suffix = val.to_string();
                line = excise(&line, start, end);
            }
        }
        _ => {}
    }

    // Step 9: Construct mods
    let (names, name_tags) = match mod_name_result {
        Some((n, t)) => (n, t),
        None => {
            // Special cases: RegenFlat/RegenPercent/DegenFlat/DegenPercent/Degen use captures for name
            match &form_type {
                FormType::RegenFlat | FormType::RegenPercent => {
                    let resource_type = form_caps_extra.as_deref().unwrap_or("");
                    if let Some(val) = REGEN_TYPES.get(resource_type) {
                        (val.clone(), vec![])
                    } else {
                        return vec![];
                    }
                }
                FormType::DegenFlat | FormType::DegenPercent => {
                    let resource_type = form_caps_extra.as_deref().unwrap_or("");
                    if let Some(val) = DEGEN_TYPES.get(resource_type) {
                        (val.clone(), vec![])
                    } else {
                        return vec![];
                    }
                }
                FormType::Degen => {
                    let dmg_type = form_caps_extra.as_deref().unwrap_or("");
                    if let Some(val) = DMG_TYPES.get(dmg_type) {
                        (vec![format!("{}Degen", val)], vec![])
                    } else {
                        return vec![];
                    }
                }
                FormType::Dmg | FormType::DmgAttacks | FormType::DmgSpells | FormType::DmgBoth => {
                    // Handled below in the damage section
                    (vec![], vec![])
                }
                _ => return vec![],
            }
        }
    };

    // Combine all flags and tags
    let combined_flags = pre_flags | mod_flag_flags;
    let combined_kw = pre_keyword_flags | mod_flag_kw;
    let mut all_tags: Vec<ModTag> = Vec::new();
    all_tags.extend(pre_tags);
    all_tags.extend(name_tags);
    all_tags.extend(mod_flag_tags);
    all_tags.extend(mod_tags);

    // Determine modType and modValue from form
    let mut mods = Vec::new();

    match &form_type {
        FormType::Inc => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Inc,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Red => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Inc,
                    value: ModValue::Number(-form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::More => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::More,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Less => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::More,
                    value: ModValue::Number(-form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Base | FormType::Gain | FormType::Chance => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Lose | FormType::Removes => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Base,
                    value: ModValue::Number(-form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Grants | FormType::GrantsGlobal => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Flag => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Flag,
                    value: ModValue::Bool(true),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Pen => {
            for name in &names {
                mods.push(Mod {
                    name: name.clone(),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Override => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Override,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::RegenFlat => {
            for name in &names {
                mods.push(Mod {
                    name: name.clone(),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::RegenPercent => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}Percent", name),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::DegenFlat => {
            for name in &names {
                mods.push(Mod {
                    name: name.clone(),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::DegenPercent => {
            for name in &names {
                mods.push(Mod {
                    name: format!("{}Percent", name),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Degen => {
            for name in &names {
                mods.push(Mod {
                    name: name.clone(),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::TotalCost | FormType::BaseCost => {
            for name in &names {
                mods.push(Mod {
                    name: name.clone(),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Dmg | FormType::DmgAttacks | FormType::DmgSpells | FormType::DmgBoth => {
            // Damage range — need min/max from captures
            // form_num is first capture, form_caps_extra has the damage type
            // Actually for DMG, we have 3 captures: min, max, type
            // We already have form_num as the first cap, but we need the second and third
            // For now emit a simple version
            // TODO: proper damage range handling
            for name in &names {
                mods.push(Mod {
                    name: format!("{}{}", name, mod_suffix),
                    mod_type: ModType::Base,
                    value: ModValue::Number(form_num),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
        FormType::Doubled => {
            // Doubled = MORE(100) + OVERRIDE(1) with multiplier limit tag
            for name in &names {
                let name_str = format!("{}{}", name, mod_suffix);
                // MORE 100%
                let mut more_tags = all_tags.clone();
                more_tags.push(ModTag::Multiplier {
                    var: format!("{}Doubled", name_str),
                    div: 1.0,
                    limit: Some(100.0),
                    base: 0.0,
                });
                mods.push(Mod {
                    name: name_str.clone(),
                    mod_type: ModType::More,
                    value: ModValue::Number(100.0),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: more_tags,
                    source: source.clone(),
                });
                // OVERRIDE 1 for the multiplier
                mods.push(Mod {
                    name: format!("Multiplier:{}Doubled", name_str),
                    mod_type: ModType::Override,
                    value: ModValue::Number(1.0),
                    flags: combined_flags,
                    keyword_flags: combined_kw,
                    tags: all_tags.clone(),
                    source: source.clone(),
                });
            }
        }
    }

    // Handle addToMinion, addToAura, etc. wrappers
    if add_to_aura && !mods.is_empty() {
        let wrapped: Vec<Mod> = mods.into_iter().map(|m| {
            Mod {
                name: "ExtraAuraEffect".to_string(),
                mod_type: ModType::List,
                value: ModValue::String(format!("mod:{}", m.name)),
                flags: ModFlags::NONE,
                keyword_flags: KeywordFlags::NONE,
                tags: vec![],
                source: source.clone(),
            }
        }).collect();
        return wrapped;
    }
    if new_aura && !mods.is_empty() {
        let wrapped: Vec<Mod> = mods.into_iter().map(|m| {
            Mod {
                name: "ExtraAura".to_string(),
                mod_type: ModType::List,
                value: ModValue::String(format!("mod:{}", m.name)),
                flags: ModFlags::NONE,
                keyword_flags: KeywordFlags::NONE,
                tags: vec![],
                source: source.clone(),
            }
        }).collect();
        return wrapped;
    }
    if add_to_minion && !mods.is_empty() {
        let wrapped: Vec<Mod> = mods.into_iter().map(|m| {
            Mod {
                name: "MinionModifier".to_string(),
                mod_type: ModType::List,
                value: ModValue::String(format!("mod:{}", m.name)),
                flags: ModFlags::NONE,
                keyword_flags: KeywordFlags::NONE,
                tags: vec![],
                source: source.clone(),
            }
        }).collect();
        return wrapped;
    }
    if apply_to_enemy && !mods.is_empty() {
        let wrapped: Vec<Mod> = mods.into_iter().map(|m| {
            Mod {
                name: "EnemyModifier".to_string(),
                mod_type: ModType::List,
                value: ModValue::String(format!("mod:{}", m.name)),
                flags: ModFlags::NONE,
                keyword_flags: KeywordFlags::NONE,
                tags: vec![],
                source: source.clone(),
            }
        }).collect();
        return wrapped;
    }

    mods
}

/// Scan form patterns and extract form type + numeric value + extra capture.
fn scan_form_patterns(line: &str) -> Option<(FormType, f64, Option<String>)> {
    if let Some((idx, caps, _start, _end)) = scan_regex(line, &*FORM_PATTERNS) {
        let form = &FORM_PATTERNS[idx].1;
        let num_str = caps.get(1).map(|m| m.as_str()).unwrap_or("0");
        let num: f64 = num_str.parse().unwrap_or(0.0);
        let extra = caps.get(2).map(|m| m.as_str().to_string());
        Some((form.clone(), num, extra))
    } else {
        None
    }
}

/// Scan pre-flag patterns (from the Lazy<Vec<...>>).
fn scan_regex_for_pre_flags<'a>(line: &'a str, patterns: &[(Lazy<Regex>, StaticPreFlagEntry)]) -> Option<(usize, regex::Captures<'a>, usize, usize)> {
    let mut best: Option<(usize, usize, usize, usize, usize)> = None;

    for (i, (re, _)) in patterns.iter().enumerate() {
        if let Some(m) = re.find(line) {
            let start = m.start();
            let end = m.end();
            let match_len = end - start;
            let pat_len = re.as_str().len();

            let is_better = match best {
                None => true,
                Some((_, bs, _be, bml, bpl)) => {
                    start < bs
                        || (start == bs && match_len > bml)
                        || (start == bs && match_len == bml && pat_len > bpl)
                }
            };

            if is_better {
                best = Some((i, start, end, match_len, pat_len));
            }
        }
    }

    if let Some((idx, start, end, _, _)) = best {
        let re = &patterns[idx].0;
        let caps = re.captures(line)?;
        Some((idx, caps, start, end))
    } else {
        None
    }
}

/// Scan mod tag patterns (from the Lazy<Vec<...>>).
fn scan_regex_for_mod_tags<'a>(line: &'a str, patterns: &[(Lazy<Regex>, StaticModTagEntry)]) -> Option<(usize, regex::Captures<'a>, usize, usize)> {
    let mut best: Option<(usize, usize, usize, usize, usize)> = None;

    for (i, (re, _)) in patterns.iter().enumerate() {
        if let Some(m) = re.find(line) {
            let start = m.start();
            let end = m.end();
            let match_len = end - start;
            let pat_len = re.as_str().len();

            let is_better = match best {
                None => true,
                Some((_, bs, _be, bml, bpl)) => {
                    start < bs
                        || (start == bs && match_len > bml)
                        || (start == bs && match_len == bml && pat_len > bpl)
                }
            };

            if is_better {
                best = Some((i, start, end, match_len, pat_len));
            }
        }
    }

    if let Some((idx, start, end, _, _)) = best {
        let re = &patterns[idx].0;
        let caps = re.captures(line)?;
        Some((idx, caps, start, end))
    } else {
        None
    }
}

/// Find the earliest plain-text substring match among keys in a Lazy<HashMap<&str, Vec<String>>>.
fn scan_plain_vec<'a>(line: &str, map: &'a HashMap<&str, Vec<String>>) -> Option<(&'a str, usize, usize, &'a Vec<String>)> {
    let lower = line.to_lowercase();
    let mut best: Option<(&'a str, usize, usize, &'a Vec<String>)> = None;

    for (key, val) in map.iter() {
        if let Some(pos) = lower.find(key) {
            let end = pos + key.len();
            let is_better = match best {
                None => true,
                Some((_, bs, be, _)) => {
                    let best_len = be - bs;
                    let this_len = end - pos;
                    pos < bs
                        || (pos == bs && this_len > best_len)
                        || (pos == bs && this_len == best_len && key.len() > (be - bs))
                }
            };
            if is_better {
                best = Some((key, pos, end, val));
            }
        }
    }

    best
}

"##,
    );
}

// ────────────────────────────────────────────────────────────────────────────
// Count constants
// ────────────────────────────────────────────────────────────────────────────

fn emit_count_constants(out: &mut String, special_mods: &[SpecialModEntry]) {
    let total = special_mods.len();
    let manual = special_mods
        .iter()
        .filter(|e| matches!(e.template, SpecialModTemplate::ManualRequired { .. }))
        .count();
    let templated = total - manual;

    out.push_str(&format!(
        "/// Number of templated (auto-generated handler) special mod entries.\n\
         pub const GENERATED_SPECIAL_COUNT: usize = {};\n\
         /// Number of manual handler special mod entries.\n\
         pub const MANUAL_SPECIAL_COUNT: usize = {};\n\
         /// Total number of special mod entries.\n\
         pub const TOTAL_SPECIAL_COUNT: usize = {};\n",
        templated, manual, total
    ));
}

// ────────────────────────────────────────────────────────────────────────────
// Helper utilities
// ────────────────────────────────────────────────────────────────────────────

fn form_type_to_rust(form: &FormType) -> &'static str {
    match form {
        FormType::Inc => "Inc",
        FormType::Red => "Red",
        FormType::More => "More",
        FormType::Less => "Less",
        FormType::Base => "Base",
        FormType::Gain => "Gain",
        FormType::Lose => "Lose",
        FormType::Grants => "Grants",
        FormType::Removes => "Removes",
        FormType::Chance => "Chance",
        FormType::Flag => "Flag",
        FormType::TotalCost => "TotalCost",
        FormType::BaseCost => "BaseCost",
        FormType::Pen => "Pen",
        FormType::RegenFlat => "RegenFlat",
        FormType::RegenPercent => "RegenPercent",
        FormType::DegenFlat => "DegenFlat",
        FormType::DegenPercent => "DegenPercent",
        FormType::Degen => "Degen",
        FormType::Dmg => "Dmg",
        FormType::DmgAttacks => "DmgAttacks",
        FormType::DmgSpells => "DmgSpells",
        FormType::DmgBoth => "DmgBoth",
        FormType::Override => "Override",
        FormType::Doubled => "Doubled",
    }
}

fn lua_mod_type_to_rust(lua_type: &str) -> &'static str {
    match lua_type.trim_matches('"') {
        "BASE" => "ModType::Base",
        "INC" => "ModType::Inc",
        "MORE" => "ModType::More",
        "FLAG" => "ModType::Flag",
        "LIST" => "ModType::List",
        "OVERRIDE" => "ModType::Override",
        "MAX" => "ModType::Max",
        _ => "ModType::Base",
    }
}

fn lua_value_to_rust(value: &str, mod_type: &str) -> String {
    let trimmed = value.trim();

    // Boolean
    if trimmed == "true" {
        return "ModValue::Bool(true)".to_string();
    }
    if trimmed == "false" {
        return "ModValue::Bool(false)".to_string();
    }

    // String value (quoted)
    if trimmed.starts_with('"') && trimmed.ends_with('"') {
        let inner = &trimmed[1..trimmed.len() - 1];
        return format!(
            "ModValue::String(\"{}\".to_string())",
            escape_rust_string(inner)
        );
    }

    // Variable references from captures (e.g. "num", "cap1")
    if trimmed == "num" || trimmed == "cap1" {
        return "ModValue::Number(num)".to_string();
    }
    if trimmed == "-num" {
        return "ModValue::Number(-num)".to_string();
    }

    // Numeric literal
    if let Ok(n) = trimmed.parse::<f64>() {
        return format!("ModValue::Number({:.1})", n);
    }

    // Complex table/expression — default to num
    if trimmed.contains("tonumber") || trimmed.contains("cap") {
        return "ModValue::Number(num)".to_string();
    }

    // Fallback
    format!(
        "ModValue::Number(0.0) /* TODO: {} */",
        escape_rust_string(trimmed)
    )
}

fn emit_mod_flags_expr(flags: &[String]) -> String {
    if flags.is_empty() {
        return "ModFlags::NONE".to_string();
    }
    let flag_str = &flags[0];
    parse_mod_flags_expr(flag_str)
}

fn parse_mod_flags_expr(s: &str) -> String {
    let trimmed = s.trim();
    if trimmed == "0" || trimmed.is_empty() {
        return "ModFlags::NONE".to_string();
    }

    // Handle bor(...) or ModFlag.X patterns
    let cleaned = trimmed.replace("bor(", "").replace(')', "");
    let parts: Vec<&str> = cleaned
        .split(',')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();

    let mut exprs = Vec::new();
    for part in &parts {
        // Also handle `|` separated
        for sub in part.split('|') {
            let sub = sub.trim();
            if sub == "0" || sub.is_empty() {
                continue;
            }
            if let Some(flag) = translate_mod_flag(sub) {
                exprs.push(flag);
            }
        }
    }

    if exprs.is_empty() {
        "ModFlags::NONE".to_string()
    } else if exprs.len() == 1 {
        exprs[0].clone()
    } else {
        // Use BitOr: ModFlags::X | ModFlags::Y — this returns ModFlags
        exprs.join(" | ")
    }
}

fn translate_mod_flag(s: &str) -> Option<String> {
    let s = s.trim();
    if s.starts_with("ModFlag.") {
        let name = &s[8..];
        match name {
            "Attack" => Some("ModFlags::ATTACK".into()),
            "Spell" => Some("ModFlags::SPELL".into()),
            "Hit" => Some("ModFlags::HIT".into()),
            "Dot" => Some("ModFlags::DOT".into()),
            "Cast" => Some("ModFlags::CAST".into()),
            "Melee" => Some("ModFlags::MELEE".into()),
            "Area" => Some("ModFlags::AREA".into()),
            "Projectile" => Some("ModFlags::PROJECTILE".into()),
            "Ailment" => Some("ModFlags::AILMENT".into()),
            "MeleeHit" => Some("ModFlags::MELEE_HIT".into()),
            "Weapon" => Some("ModFlags::WEAPON".into()),
            "Axe" => Some("ModFlags::AXE".into()),
            "Bow" => Some("ModFlags::BOW".into()),
            "Claw" => Some("ModFlags::CLAW".into()),
            "Dagger" => Some("ModFlags::DAGGER".into()),
            "Mace" => Some("ModFlags::MACE".into()),
            "Staff" => Some("ModFlags::STAFF".into()),
            "Sword" => Some("ModFlags::SWORD".into()),
            "Wand" => Some("ModFlags::WAND".into()),
            "Unarmed" => Some("ModFlags::UNARMED".into()),
            "WeaponMelee" => Some("ModFlags::WEAPON_MELEE".into()),
            "WeaponRanged" => Some("ModFlags::WEAPON_RANGED".into()),
            "Weapon1H" => Some("ModFlags::WEAPON_1H".into()),
            "Weapon2H" => Some("ModFlags::WEAPON_2H".into()),
            _ => Some(format!("ModFlags::NONE /* unknown: {} */", name)),
        }
    } else if let Ok(n) = s.parse::<u32>() {
        Some(format!("ModFlags(0x{:X})", n))
    } else {
        Some(format!("ModFlags::NONE /* {} */", s))
    }
}

fn emit_keyword_flags_expr(kw: &[String]) -> String {
    if kw.is_empty() {
        return "KeywordFlags::NONE".to_string();
    }
    let kw_str = &kw[0];
    parse_keyword_flags_expr(kw_str)
}

fn parse_keyword_flags_expr(s: &str) -> String {
    let trimmed = s.trim();
    if trimmed == "0" || trimmed.is_empty() {
        return "KeywordFlags::NONE".to_string();
    }

    let cleaned = trimmed.replace("bor(", "").replace(')', "");
    let parts: Vec<&str> = cleaned
        .split(',')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();

    let mut exprs = Vec::new();
    for part in &parts {
        for sub in part.split('|') {
            let sub = sub.trim();
            if sub == "0" || sub.is_empty() {
                continue;
            }
            if let Some(flag) = translate_keyword_flag(sub) {
                exprs.push(flag);
            }
        }
    }

    if exprs.is_empty() {
        "KeywordFlags::NONE".to_string()
    } else if exprs.len() == 1 {
        exprs[0].clone()
    } else {
        // Use BitOr: KeywordFlags::X | KeywordFlags::Y — this returns KeywordFlags
        exprs.join(" | ")
    }
}

fn translate_keyword_flag(s: &str) -> Option<String> {
    let s = s.trim();
    if s.starts_with("KeywordFlag.") {
        let name = &s[12..];
        match name {
            "Aura" => Some("KeywordFlags::AURA".into()),
            "Curse" => Some("KeywordFlags::CURSE".into()),
            "Warcry" => Some("KeywordFlags::WARCRY".into()),
            "Movement" => Some("KeywordFlags::MOVEMENT".into()),
            "Physical" => Some("KeywordFlags::PHYSICAL".into()),
            "Fire" => Some("KeywordFlags::FIRE".into()),
            "Cold" => Some("KeywordFlags::COLD".into()),
            "Lightning" => Some("KeywordFlags::LIGHTNING".into()),
            "Chaos" => Some("KeywordFlags::CHAOS".into()),
            "Vaal" => Some("KeywordFlags::VAAL".into()),
            "Bow" => Some("KeywordFlags::BOW".into()),
            "Arrow" => Some("KeywordFlags::ARROW".into()),
            "Trap" => Some("KeywordFlags::TRAP".into()),
            "Mine" => Some("KeywordFlags::MINE".into()),
            "Totem" => Some("KeywordFlags::TOTEM".into()),
            "Minion" => Some("KeywordFlags::MINION".into()),
            "Attack" => Some("KeywordFlags::ATTACK".into()),
            "Spell" => Some("KeywordFlags::SPELL".into()),
            "Hit" => Some("KeywordFlags::HIT".into()),
            "Ailment" => Some("KeywordFlags::AILMENT".into()),
            "Brand" => Some("KeywordFlags::BRAND".into()),
            "Poison" => Some("KeywordFlags::POISON".into()),
            "Bleed" => Some("KeywordFlags::BLEED".into()),
            "Ignite" => Some("KeywordFlags::IGNITE".into()),
            "PhysicalDot" => Some("KeywordFlags::PHYSICAL_DOT".into()),
            "LightningDot" => Some("KeywordFlags::LIGHTNING_DOT".into()),
            "ColdDot" => Some("KeywordFlags::COLD_DOT".into()),
            "FireDot" => Some("KeywordFlags::FIRE_DOT".into()),
            "ChaosDot" => Some("KeywordFlags::CHAOS_DOT".into()),
            "MatchAll" => Some("KeywordFlags::MATCH_ALL".into()),
            _ => Some(format!("KeywordFlags::NONE /* unknown: {} */", name)),
        }
    } else if let Ok(n) = s.parse::<u32>() {
        Some(format!("KeywordFlags(0x{:X})", n))
    } else {
        Some(format!("KeywordFlags::NONE /* {} */", s))
    }
}

fn emit_static_tags(tags: &[LuaTag]) -> String {
    if tags.is_empty() {
        return String::new();
    }
    let items: Vec<String> = tags.iter().map(|t| emit_single_static_tag(t)).collect();
    items.join(", ")
}

fn emit_static_tag_vec_items(tags: &[LuaTag]) -> String {
    emit_static_tags(tags)
}

fn emit_single_static_tag(tag: &LuaTag) -> String {
    match tag.tag_type.as_str() {
        "Condition" => {
            let var = get_tag_field(tag, "var").unwrap_or_default();
            let neg = get_tag_field(tag, "neg")
                .map(|s| s == "true")
                .unwrap_or(false);
            format!(
                "StaticTag::Condition {{ var: \"{}\".to_string(), neg: {} }}",
                escape_rust_string(&var),
                neg
            )
        }
        "Multiplier" => {
            let var = get_tag_field(tag, "var").unwrap_or_default();
            let div = get_tag_field(tag, "div")
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(1.0);
            let limit = get_tag_field(tag, "limit")
                .or_else(|| get_tag_field(tag, "globalLimit"))
                .and_then(|s| s.parse::<f64>().ok());
            let base = get_tag_field(tag, "base")
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(0.0);
            let limit_str = match limit {
                Some(l) => format!("Some({:.1})", l),
                None => "None".to_string(),
            };
            format!(
                "StaticTag::Multiplier {{ var: \"{}\".to_string(), div: {:.1}, limit: {}, base: {:.1} }}",
                escape_rust_string(&var),
                div,
                limit_str,
                base
            )
        }
        "MultiplierThreshold" => {
            let var = get_tag_field(tag, "var").unwrap_or_default();
            let threshold = get_tag_field(tag, "threshold")
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(0.0);
            let upper = get_tag_field(tag, "upper")
                .map(|s| s == "true")
                .unwrap_or(false);
            format!(
                "StaticTag::MultiplierThreshold {{ var: \"{}\".to_string(), threshold: {:.1}, upper: {} }}",
                escape_rust_string(&var),
                threshold,
                upper
            )
        }
        "PerStat" => {
            let stat = get_tag_field(tag, "stat").unwrap_or_default();
            let div = get_tag_field(tag, "div")
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(1.0);
            let limit = get_tag_field(tag, "limit").and_then(|s| s.parse::<f64>().ok());
            let base = get_tag_field(tag, "base")
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(0.0);
            let limit_str = match limit {
                Some(l) => format!("Some({:.1})", l),
                None => "None".to_string(),
            };
            format!(
                "StaticTag::PerStat {{ stat: \"{}\".to_string(), div: {:.1}, limit: {}, base: {:.1} }}",
                escape_rust_string(&stat),
                div,
                limit_str,
                base
            )
        }
        "StatThreshold" => {
            let stat = get_tag_field(tag, "stat").unwrap_or_default();
            let threshold = get_tag_field(tag, "threshold")
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(0.0);
            let upper = get_tag_field(tag, "upper")
                .map(|s| s == "true")
                .unwrap_or(false);
            format!(
                "StaticTag::StatThreshold {{ stat: \"{}\".to_string(), threshold: {:.1}, upper: {} }}",
                escape_rust_string(&stat),
                threshold,
                upper
            )
        }
        "GlobalEffect" => {
            let effect_type = get_tag_field(tag, "effectType").unwrap_or_default();
            let unscalable = get_tag_field(tag, "unscalable")
                .map(|s| s == "true")
                .unwrap_or(false);
            format!(
                "StaticTag::GlobalEffect {{ effect_type: \"{}\".to_string(), unscalable: {} }}",
                escape_rust_string(&effect_type),
                unscalable
            )
        }
        "SkillName" => {
            let name = get_tag_field(tag, "skillName").unwrap_or_default();
            format!(
                "StaticTag::SkillName {{ name: \"{}\".to_string() }}",
                escape_rust_string(&name)
            )
        }
        "SkillId" => {
            let id = get_tag_field(tag, "skillId").unwrap_or_default();
            format!(
                "StaticTag::SkillId {{ id: \"{}\".to_string() }}",
                escape_rust_string(&id)
            )
        }
        "SkillType" => {
            let skill_type = get_tag_field(tag, "skillType").unwrap_or_default();
            // Try to parse as number, otherwise use 0
            let num = skill_type.parse::<u32>().unwrap_or(0);
            format!("StaticTag::SkillType {{ skill_type: {} }}", num)
        }
        "SlotName" => {
            let slot = get_tag_field(tag, "slotName").unwrap_or_default();
            let neg = get_tag_field(tag, "neg")
                .map(|s| s == "true")
                .unwrap_or(false);
            format!(
                "StaticTag::SlotName {{ slot_name: \"{}\".to_string(), neg: {} }}",
                escape_rust_string(&slot),
                neg
            )
        }
        "SocketedIn" => {
            let slot = get_tag_field(tag, "slotName").unwrap_or_default();
            format!(
                "StaticTag::SocketedIn {{ slot_name: \"{}\".to_string() }}",
                escape_rust_string(&slot)
            )
        }
        "ItemCondition" => {
            let var = get_tag_field(tag, "var").unwrap_or_default();
            let neg = get_tag_field(tag, "neg")
                .map(|s| s == "true")
                .unwrap_or(false);
            format!(
                "StaticTag::ItemCondition {{ var: \"{}\".to_string(), neg: {} }}",
                escape_rust_string(&var),
                neg
            )
        }
        "ActorCondition" => {
            let actor = get_tag_field(tag, "actor").unwrap_or_default();
            let var = get_tag_field(tag, "var").unwrap_or_default();
            let neg = get_tag_field(tag, "neg")
                .map(|s| s == "true")
                .unwrap_or(false);
            format!(
                "StaticTag::ActorCondition {{ actor: \"{}\".to_string(), var: \"{}\".to_string(), neg: {} }}",
                escape_rust_string(&actor),
                escape_rust_string(&var),
                neg
            )
        }
        "Limit" => {
            let limit = get_tag_field(tag, "limit")
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(0.0);
            format!("StaticTag::Limit {{ limit: {:.1} }}", limit)
        }
        "ModFlagOr" => {
            let flags = get_tag_field(tag, "modFlags").unwrap_or_default();
            let flags_expr = parse_mod_flags_expr(&flags);
            format!("StaticTag::ModFlagOr {{ mod_flags: {} }}", flags_expr)
        }
        "KeywordFlagAnd" => {
            let flags = get_tag_field(tag, "keywordFlags").unwrap_or_default();
            let flags_expr = parse_keyword_flags_expr(&flags);
            format!(
                "StaticTag::KeywordFlagAnd {{ keyword_flags: {} }}",
                flags_expr
            )
        }
        _ => {
            let raw = format!("{:?}", tag);
            format!(
                "StaticTag::Unknown {{ raw: \"{}\".to_string() }}",
                escape_rust_string(&raw)
            )
        }
    }
}

fn get_tag_field(tag: &LuaTag, key: &str) -> Option<String> {
    for (k, v) in &tag.fields {
        if k == key {
            return Some(v.trim_matches('"').to_string());
        }
    }
    None
}

fn emit_single_mod_flag(s: &str) -> String {
    parse_mod_flags_expr(s)
}

fn emit_single_keyword_flag(s: &str) -> String {
    parse_keyword_flags_expr(s)
}

/// Escape a string for use in a Rust string literal.
fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
